/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated/dashboard/notifications'
import { Route as AuthenticatedDashboardContractsRouteImport } from './routes/_authenticated/dashboard/contracts'
import { Route as AdminAdminServicesRouteImport } from './routes/_admin/admin/services'
import { Route as AdminAdminReleasesRouteImport } from './routes/_admin/admin/releases'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin/admin/orders'
import { Route as AdminAdminArtistsRouteImport } from './routes/_admin/admin/artists'
import { Route as AuthenticatedDashboardReleasesNewRouteImport } from './routes/_authenticated/dashboard/releases/new'
import { Route as AuthenticatedDashboardReleasesKeyRouteImport } from './routes/_authenticated/dashboard/releases/$key'
import { Route as AdminAdminReleasesKeyRouteImport } from './routes/_admin/admin/releases_.$key'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardContractsRoute =
  AuthenticatedDashboardContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AdminAdminServicesRoute = AdminAdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminReleasesRoute = AdminAdminReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminArtistsRoute = AdminAdminArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AuthenticatedDashboardReleasesNewRoute =
  AuthenticatedDashboardReleasesNewRouteImport.update({
    id: '/releases/new',
    path: '/releases/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReleasesKeyRoute =
  AuthenticatedDashboardReleasesKeyRouteImport.update({
    id: '/releases/$key',
    path: '/releases/$key',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AdminAdminReleasesKeyRoute = AdminAdminReleasesKeyRouteImport.update({
  id: '/releases_/$key',
  path: '/releases/$key',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/pricing': typeof PublicPricingRoute
  '/admin/artists': typeof AdminAdminArtistsRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/releases': typeof AdminAdminReleasesRoute
  '/admin/services': typeof AdminAdminServicesRoute
  '/dashboard/contracts': typeof AuthenticatedDashboardContractsRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/releases/$key': typeof AdminAdminReleasesKeyRoute
  '/dashboard/releases/$key': typeof AuthenticatedDashboardReleasesKeyRoute
  '/dashboard/releases/new': typeof AuthenticatedDashboardReleasesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/about': typeof PublicAboutRoute
  '/pricing': typeof PublicPricingRoute
  '/admin/artists': typeof AdminAdminArtistsRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/releases': typeof AdminAdminReleasesRoute
  '/admin/services': typeof AdminAdminServicesRoute
  '/dashboard/contracts': typeof AuthenticatedDashboardContractsRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/releases/$key': typeof AdminAdminReleasesKeyRoute
  '/dashboard/releases/$key': typeof AuthenticatedDashboardReleasesKeyRoute
  '/dashboard/releases/new': typeof AuthenticatedDashboardReleasesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/': typeof PublicIndexRoute
  '/_admin/admin/artists': typeof AdminAdminArtistsRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
  '/_admin/admin/releases': typeof AdminAdminReleasesRoute
  '/_admin/admin/services': typeof AdminAdminServicesRoute
  '/_authenticated/dashboard/contracts': typeof AuthenticatedDashboardContractsRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_admin/admin/releases_/$key': typeof AdminAdminReleasesKeyRoute
  '/_authenticated/dashboard/releases/$key': typeof AuthenticatedDashboardReleasesKeyRoute
  '/_authenticated/dashboard/releases/new': typeof AuthenticatedDashboardReleasesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/about'
    | '/pricing'
    | '/admin/artists'
    | '/admin/orders'
    | '/admin/releases'
    | '/admin/services'
    | '/dashboard/contracts'
    | '/dashboard/notifications'
    | '/admin/'
    | '/dashboard/'
    | '/admin/releases/$key'
    | '/dashboard/releases/$key'
    | '/dashboard/releases/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/about'
    | '/pricing'
    | '/admin/artists'
    | '/admin/orders'
    | '/admin/releases'
    | '/admin/services'
    | '/dashboard/contracts'
    | '/dashboard/notifications'
    | '/admin'
    | '/dashboard'
    | '/admin/releases/$key'
    | '/dashboard/releases/$key'
    | '/dashboard/releases/new'
  id:
    | '__root__'
    | '/_admin'
    | '/_authenticated'
    | '/_public'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_admin/admin'
    | '/_authenticated/dashboard'
    | '/_public/about'
    | '/_public/pricing'
    | '/_public/'
    | '/_admin/admin/artists'
    | '/_admin/admin/orders'
    | '/_admin/admin/releases'
    | '/_admin/admin/services'
    | '/_authenticated/dashboard/contracts'
    | '/_authenticated/dashboard/notifications'
    | '/_admin/admin/'
    | '/_authenticated/dashboard/'
    | '/_admin/admin/releases_/$key'
    | '/_authenticated/dashboard/releases/$key'
    | '/_authenticated/dashboard/releases/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/contracts': {
      id: '/_authenticated/dashboard/contracts'
      path: '/contracts'
      fullPath: '/dashboard/contracts'
      preLoaderRoute: typeof AuthenticatedDashboardContractsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_admin/admin/services': {
      id: '/_admin/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminAdminServicesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/releases': {
      id: '/_admin/admin/releases'
      path: '/releases'
      fullPath: '/admin/releases'
      preLoaderRoute: typeof AdminAdminReleasesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/artists': {
      id: '/_admin/admin/artists'
      path: '/artists'
      fullPath: '/admin/artists'
      preLoaderRoute: typeof AdminAdminArtistsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/dashboard/releases/new': {
      id: '/_authenticated/dashboard/releases/new'
      path: '/releases/new'
      fullPath: '/dashboard/releases/new'
      preLoaderRoute: typeof AuthenticatedDashboardReleasesNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/releases/$key': {
      id: '/_authenticated/dashboard/releases/$key'
      path: '/releases/$key'
      fullPath: '/dashboard/releases/$key'
      preLoaderRoute: typeof AuthenticatedDashboardReleasesKeyRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_admin/admin/releases_/$key': {
      id: '/_admin/admin/releases_/$key'
      path: '/releases/$key'
      fullPath: '/admin/releases/$key'
      preLoaderRoute: typeof AdminAdminReleasesKeyRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminArtistsRoute: typeof AdminAdminArtistsRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
  AdminAdminReleasesRoute: typeof AdminAdminReleasesRoute
  AdminAdminServicesRoute: typeof AdminAdminServicesRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminReleasesKeyRoute: typeof AdminAdminReleasesKeyRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminArtistsRoute: AdminAdminArtistsRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
  AdminAdminReleasesRoute: AdminAdminReleasesRoute,
  AdminAdminServicesRoute: AdminAdminServicesRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminReleasesKeyRoute: AdminAdminReleasesKeyRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardContractsRoute: typeof AuthenticatedDashboardContractsRoute
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardReleasesKeyRoute: typeof AuthenticatedDashboardReleasesKeyRoute
  AuthenticatedDashboardReleasesNewRoute: typeof AuthenticatedDashboardReleasesNewRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardContractsRoute: AuthenticatedDashboardContractsRoute,
    AuthenticatedDashboardNotificationsRoute:
      AuthenticatedDashboardNotificationsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardReleasesKeyRoute:
      AuthenticatedDashboardReleasesKeyRoute,
    AuthenticatedDashboardReleasesNewRoute:
      AuthenticatedDashboardReleasesNewRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
